name: Update File

on:
  schedule:
    - cron: '57 21 * * *'

jobs:
  update:
    name: Update File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run script
        run: ./scripts/update_file.sh
