name: Update File

on:
  schedule:
    - cron: '15 01 * * *'
  workflow_dispatch:
  
jobs:
  update:
    name: Update File
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run script
        shell: bash
        run: ./scripts/update_file.sh arg1 arg2
