name: Update File

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    name: Update File
    runs-on: ubuntu-latest
    steps:
      - name: Run script
        run: |
          # Pfad zur Textdatei
          file_path="file_context.txt"

          # Aktuelles Datum in Europäischer Zeit
          Date=$(TZ="Europe/Berlin" date +"%d.%m.%Y")

          # Datum in Datei ersetzen
          sed -i "s/Date:.*/Date: $Date/" "$file_path"

          # Commit and push changes
          git config --global user.name "Your Name"
          git add "$file_path"
          git commit -m "Update File"
          git push
