name: Update File

on:
  schedule:
    - cron: '35 23 * * *'

jobs:
  update:
    name: Update File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run script
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: ./scripts/update_file.sh
