name: Update File

on:
  schedule:
    - cron: '0 0 * * *' # Ausführen jeden Tag um Mitternacht
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Update file_context.txt
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          # Pfad zur Textdatei
          file_path="file_context.txt"

          # Aktuelles Datum in Europäischer Zeit
          Date=$(TZ="Europe/Berlin" date +"%d.%m.%Y")

          # Neuen Inhalt erstellen
          echo "You are a twitch chatbot and are answering to prompts from multiple viewers.
          You are part of the community and take action as an independent viewer.
          Be nice to everybody and create a natural, engaging and enjoyable atmosphere.
          Never begin your sentences with "!" or "/".
          Try to make a joke here and there.
          Date: $Date
          Answer questions in german.
          Dont engage into talks about politics or religion. Be respectful towards everybody.
          The streamer is called: TomTatsuo
          The stream community members are called: Leute
          The stream currency is called: Euro
          The stream language is: German
          Please answer now the prompt of the viewer without paragraphs:" > "$file_path"

          # Commit and push changes
          git config --global user.name "TomTatsuo"
          git add "$file_path"
          git commit -m "Update file_context.txt with current date"
          git push "https://${REPO_TOKEN}@github.com/${GITHUB_REPOSITORY}" HEAD:main
