name: Update File

on:
  schedule:
    - cron: '15 01 * * *'
  workflow_dispatch:
  
jobs:
  update:
    name: Update File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Run script
        run: ./scripts/update_file.sh
