name: Update File

on:
  schedule:
    - cron: '0 0 * * *' # Ausführen jeden Tag um Mitternacht
  workflow_dispatch:

jobs:
  update:
    name: Update File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Git
        run: |
          git config --global user.name "TomTatsuo"
          git config --global user.email "youremail@example.com"
      - name: Run script
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          chmod +x ./scripts/update_file.sh
          ./scripts/update_file.sh
          git add file_context.txt
          git commit -m "Update file_context.txt"
          git push origin main
