name: Update File

on:
  schedule:
    - cron: '44 21 * * *'

jobs:
  update:
    name: Update File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update File
        run: |
          # Pfad zur Textdatei
          file_path="file_context.txt"

          # Aktuelles Datum in Europäischer Zeit
          Date=$(TZ="Europe/Berlin" date +"%d.%m.%Y")

          # Datum in Datei ersetzen
          sed -i "s/Date:.*/Date: $Date/" "$file_path"

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update File"
